/*============= BEGIN ORIGINAL SQL FILE NAME:  \Code Scripts\IPMO Transaction Generator SPs\spIGEN_FILLIRDbyConditions__generated.sql =============*/
print ' Start of original SQL file:   \Code Scripts\IPMO Transaction Generator SPs\spIGEN_FILLIRDbyConditions__generated.sql ' 

if exists (select * from dbo.sysobjects where id = object_id(N'[dbo].[spIGEN_FILLIRDbyConditions__generated]') and OBJECTPROPERTY(id, N'IsProcedure') = 1)
drop Procedure [dbo].[spIGEN_FILLIRDbyConditions__generated]
GO


CREATE Procedure spIGEN_FILLIRDbyConditions__generated(@ClearingNetwork int)
as

-- DELIBERATELY EMPTY SP

-- THIS SP is auto-generated by the database build scripts, so that we can auto-gen the IRD calculations from XML.
-- This is to make it safer and easier to maintain the IRD calculations from the Mastercard specs.

--{IRD_INSERT_POINT}

GO
print ' End of original SQL file:   \Code Scripts\IPMO Transaction Generator SPs\spIGEN_FILLIRDbyConditions__generated.sql ' 
/*============= END ORIGINAL SQL FILE NAME:  \Code Scripts\IPMO Transaction Generator SPs\spIGEN_FILLIRDbyConditions__generated.sql =============*/
