
-- === IRD 20 ====================================================================
-- This SQL was autogenerated from XML to calculate if this IRD matches the transactions
INSERT INTO CW_IPMO_IRDbyConditions
SELECT DISTINCT
	mt.id,
	'20',
	CONVERT(int, CASE md.SICCode
				 WHEN 6010 THEN -- mcc is cash advance
 					CASE mt.ProcessingType 
  					WHEN '01' then '12' 
  					ELSE mt.ProcessingType
  					END
  				 ELSE mt.ProcessingType
  				 END)
FROM
	aw_mtf_transaction mt 
	INNER JOIN CS_IPM_Bin ab on ab.AcquiringBINID = @BIN 
	INNER JOIN AW_MTF_TransactionDetails mtd on mtd.MTFKey = mt.ID
	--CS_IPM_BinRange ibr on mtd.BinKey = ibr.ID INNER JOIN
	left outer join
	ac_userbin ub on ub.id = mtd.BinKey
	and ub.MasterCardBranded = 1
	inner join
	CS_IPM_BinRange ibr on
	(
		
		/*PRN:44788 - User BINs (Collection Only) transactions were matched to wrong binrange (This is the same fix that was used for PRN:45295.)*/
		(
			mtd.ClearingNetwork < 10 --NOT User Bin
			and mtd.BinKey = ibr.ID
		)
		or
		(
			mtd.ClearingNetwork > 9 --User Bin
			and ub.MasterCardBinKey = ibr.ID
			and ub.id = mtd.BinKey
			and ub.MasterCardBranded = 1
		)
	)
	inner join MC_Merchant md on md.MerchantKey = mtd.MerchantKey 
	INNER JOIN CS_IPM_MCC mcc on mcc.MCC = md.SICCode
	--my ExtraSQLjoin
WHERE
	mtd.status = 5 --MTF transaction is valid and ready to process
	and mtd.ClearingNetwork = @ClearingNetwork
	and ibr.ProductType = 1 -- 1 = Consumer, 2 = Producer
	and ProcessingType in ('18', '20') --ProcessingType is Processing Code in the spec
	and (not 0 or datediff(day, convert(datetime, left(mt.TransDateTime, 6), 12), @now) < 0 )-- timeliness
	and (not 1 or mt.ApprovalCode <> '000000' )-- approval code
	and mcc.CABProgram in ('A001', 'D001')
	and ibr.AcceptanceBrand in ('MCC', 'DMC')
	and
	(
		--template for Region + Product conditions:
		(
			(
			(ab.region in ('A', 'D', 'B', 'E', '1') and ibr.region = 'C') --region
			)
			and 
			(
				(ibr.AcceptanceBrand = 'MCC' and ibr.ProductID in ('MBK', 'MCC', 'MCG', 'MCS', 'MCT', 'MCV', 'MCW', 'MNW', 'MPL', 'MRG', 'MWE') ) -- GCMS Product ID
				or
				(ibr.AcceptanceBrand = 'DMC' and ibr.ProductID in ('MCD', 'MDG', 'MDH', 'MDJ', 'MDO', 'MDP', 'MDR', 'MDS', 'MPG', 'MPP') ) -- GCMS Product ID
			)
		)
	)
	and
	(
		--my ExtraSQLwhere
	)
